@echo off
echo Cleaning bin and obj...
if exist bin rd /s /q bin
if exist obj rd /s /q obj
echo Building release...
dotnet build CsSimConnect.csproj -c Release
if errorlevel 1 goto :eof
echo Packing...
dotnet pack CsSimConnect.csproj -c Release --no-build -o dist
